version: "3.9"

services:

  postgres:
    container_name: connectfield_db
    image: postgres:14.2
    environment:
      POSTGRES_USER: connectfield
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - connectfield-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - connectfield-redis:/var/lib/redis/data

  connectfield:
    container_name: connectfield
    build:
      context: .
    volumes:
      - ./connectfield:/app
      - bundle_cache:/usr/local/bundle
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env


  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - connectfield
    ports:
      - '8020:8020'

volumes:
  connectfield-postgres:
  connectfield-redis:
  bundle_cache: